[General]
Font="Inter"
FontSize="11"
UiScale=1.4
HourFormat="HH:mm"
DateFormat="dddd, MMMM d"

Background="backgrounds/login-wallpaper.jpg"

AnimationDuration="150"
AnimationEasing="OutCubic"

AutoFingerprintOnLoad=true

DateTextColor="#bac2de"
TimeTextColor="#cdd6f4"

FormBackgroundColor="#181825"

LoginFieldBackgroundColor="#1e1e2e"
PasswordFieldBackgroundColor="#1e1e2e"

LoginFieldTextColor="#cdd6f4"
PasswordFieldTextColor="#cdd6f4"

PlaceholderTextColor="#6c7086"

LoginButtonTextColor="#11111b"
LoginButtonBackgroundColor="#b4befe"

SystemButtonsIconsColor="#a6adc8"
EnvironmentButtonTextColor="#a6adc8"

DropdownTextColor="#cdd6f4"
DropdownSelectedTextColor="#11111b"
DropdownBackgroundColor="#181825"
DropdownSelectedBackgroundColor="#b4befe"
DropdownBorderColor="#313244"
DropdownSelectedBorderColor="#b4befe"

HoverLoginButtonBackgroundColor="#cba6f7"
HoverSystemButtonsIconsColor="#b4befe"
HoverEnvironmentButtonTextColor="#b4befe"

Blur="0.0"
FormPosition="center"